site_name: Super Cashier Documentations

theme:
  name: "material"

plugins:
  - mkdocstrings
  - glightbox

nav:
  - Welcome to Super Cashier Apps: index.md
  - How to Use: how to use.md
  - References: reference.md
