site_name: Super Cashier Documentations
site_url: https://ryanalhakim27.github.io/datascienceanalytics/
site_description: Super Cashier App Documentation. Part of PACMANN Academy Assignment
site_author: Mohammad Ryan Alhakim

repo_url: https://github.com/ryanalhakim27/datascienceanalytics

theme:
  name: "material"

plugins:
  - mkdocstrings
  - glightbox

nav:
  - Welcome to Super Cashier Apps: index.md
  - How to Use: how to use.md
  - References: reference.md
